env:
  browser: true
  es2021: true
  jest: true
extends:
  - 'plugin:react/recommended'
  - airbnb
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
  - jest
globals:
  apiURL: true  
rules:
  arrow-parens:
    - error
    - as-needed
  array-bracket-spacing:
    - error
    - always
  object-curly-newline:
    - error
    - ImportDeclaration: never
  no-use-before-define:
    - error
    - functions: false
  react/jsx-one-expression-per-line:
    - off
  import/no-cycle:
    - off
